import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {createHash} from 'node:crypto';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {writeJsonFeed, writeRss} from '../dist/feeds.js';
import {parse, stringify} from 'yaml';
import {buildLedger, buildRegistry, readChange, readDocument, readManifest} from '../dist/manifest.js';

const V4_SCHEMA_SHA256 = 'c70b18dd8dc469eda14e681e50ae592d055a0ca0caa9b5c251103b80d1621a3d';
const essV5 = new URL('../fixtures/ess-v5.yaml', import.meta.url);

async function withManifest(mutate, check) {
  const document = parse(await fs.readFile(essV5, 'utf8'));
  mutate(document.surfaces[0]);
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'b10x-docs-v5-'));
  const file = path.join(directory, 'b10x.docs.yaml');
  try {
    await fs.writeFile(file, stringify(document), 'utf8');
    await check(file);
  } finally {
    await fs.rm(directory, {recursive: true});
  }
}

function sidebarLeaves(items) {
  return items.flatMap((item) => (typeof item === 'string' ? [item] : sidebarLeaves(item.items)));
}

test('v5 expresses the ESS curated sidebar, landing document, withheld document and built assets', async () => {
  const manifest = await readManifest(essV5);
  assert.equal(manifest.schema, 'b10x-docs/v5');
  const [surface] = manifest.surfaces;
  const {sidebar, landing, menuWithheld: withheld} = surface.source.navigation;
  assert.deepEqual(sidebar.map((category) => category.label), ['Start here', 'Concepts', 'Guides', 'Reference', 'Examples', 'Project status']);
  assert.ok(sidebar.every((category) => category.collapsed === false));
  assert.equal(sidebarLeaves(sidebar).length, 19);
  assert.equal(landing, 'docs/index.md');
  assert.deepEqual(withheld, ['docs/guides/record-realization.md']);
  assert.deepEqual(surface.builtAssets, ['static/lab/lab.js', 'static/lab/billing_web_realized.wasm']);
  assert.equal(buildRegistry([manifest]).surfaces[0].key, 'ess/docs');
});

test('v5 refuses a sidebar leaf the surface does not publish, naming the path', async () => {
  await withManifest(
    (surface) => surface.source.documents.exclude.push('docs/examples/specification-to-contracts.md'),
    (file) => assert.rejects(readManifest(file), /sidebar leaf docs\/examples\/specification-to-contracts\.md is not a published document/),
  );
});

test('v5 refuses an unpublished leaf inside a nested category', async () => {
  await withManifest(
    (surface) => surface.source.navigation.sidebar[2].items.push({label: 'Internal', items: ['docs/internal/runbook.md']}),
    (file) => assert.rejects(readManifest(file), /sidebar leaf docs\/internal\/runbook\.md is not a published document/),
  );
});

test('v5 refuses a landing or menu-withheld path the surface does not publish, naming the path', async () => {
  await withManifest(
    (surface) => { surface.source.navigation.landing = 'README.md'; },
    (file) => assert.rejects(readManifest(file), /landing README\.md is not a published document/),
  );
  await withManifest(
    (surface) => surface.source.navigation.menuWithheld.push('docs/plans/next.md'),
    (file) => assert.rejects(readManifest(file), /menuWithheld docs\/plans\/next\.md is not a published document/),
  );
  await withManifest(
    (surface) => { delete surface.source.documents; surface.source.data = {include: ['data/*.json']}; },
    (file) => assert.rejects(readManifest(file), /sidebar leaf docs\/index\.md is not a published document/),
  );
});

test('v5 still accepts the enum sidebar and refuses a glob as a sidebar leaf', async () => {
  await withManifest(
    (surface) => { surface.source.navigation = {label: 'ESS', sidebar: 'autogenerated', landing: 'docs/index.md'}; },
    async (file) => assert.equal((await readManifest(file)).surfaces[0].source.navigation.sidebar, 'autogenerated'),
  );
  await withManifest(
    (surface) => { surface.source.navigation.sidebar[0].items = ['docs/*.md']; },
    (file) => assert.rejects(readManifest(file), /does not satisfy b10x-docs\/v5/),
  );
});

test('v5 refuses the snake_case withheld key and a surface-level assets key', async () => {
  await withManifest(
    (surface) => { surface.source.navigation.menu_withheld = surface.source.navigation.menuWithheld; delete surface.source.navigation.menuWithheld; },
    (file) => assert.rejects(readManifest(file), /does not satisfy b10x-docs\/v5/),
  );
  await withManifest(
    (surface) => { surface.assets = surface.builtAssets; delete surface.builtAssets; },
    (file) => assert.rejects(readManifest(file), /does not satisfy b10x-docs\/v5/),
  );
});

test('v5 accepts a landing document that is also withheld from the menu', async () => {
  await withManifest(
    (surface) => { surface.source.navigation.landing = 'docs/guides/record-realization.md'; },
    async (file) => {
      const {landing, menuWithheld} = (await readManifest(file)).surfaces[0].source.navigation;
      assert.equal(landing, 'docs/guides/record-realization.md');
      assert.deepEqual(menuWithheld, ['docs/guides/record-realization.md']);
    },
  );
});

test('every v5 path field refuses duplicate, non-canonical and control-character spellings, naming the path', async () => {
  const cases = [
    [(surface) => surface.source.navigation.menuWithheld.push('docs/guides/record-realization.md'), /menuWithheld docs\/guides\/record-realization\.md appears more than once/],
    [(surface) => { surface.source.navigation.landing = 'docs/./index.md'; }, /landing docs\/\.\/index\.md is not a canonical path/],
    [(surface) => surface.builtAssets.push('static/lab/lab.js'), /builtAssets static\/lab\/lab\.js appears more than once/],
    [(surface) => surface.builtAssets.push('static//lab/other.js'), /builtAssets static\/\/lab\/other\.js is not a canonical path/],
    [(surface) => surface.builtAssets.push('static/lab/x\n/../../../secret.js'), /secret\.js/],
    [(surface) => { surface.source.navigation.landing = 'docs/\tindex.md'; }, /index\.md/],
    [(surface) => { surface.source.navigation.landing = 'docs/ index.md'; }, /"docs\/\\u2028index\.md"/],
    [(surface) => { surface.source.navigation.menuWithheld = ['docs/ x.md']; }, /"docs\/\\u2029x\.md"/],
    [(surface) => { surface.builtAssets = ['static/lab/\u0085lab.js']; }, /"static\/lab\/\\u0085lab\.js"/],
    [(surface) => { surface.builtAssets = ['static/lab/\u009flab.js']; }, /"static\/lab\/\\u009flab\.js"/],
    [(surface) => { surface.builtAssets = ['static/lab/?.js']; }, /"static\/lab\/\?\.js"/],
  ];
  for (const [mutate, expected] of cases) {
    await withManifest(mutate, (file) => assert.rejects(readManifest(file), expected));
  }
});

test('every invisible character is refused in a v5 path and shown as \\uXXXX', async () => {
  const codePoints = [...Array(0x20).keys(), ...Array.from({length: 0x21}, (_, index) => 0x7f + index), 0x2028, 0x2029];
  for (const codePoint of codePoints) {
    const escaped = `\\u${codePoint.toString(16).padStart(4, '0')}`;
    await withManifest(
      (surface) => { surface.builtAssets = [`static/lab/${String.fromCharCode(codePoint)}lab.js`]; },
      (file) => assert.rejects(readManifest(file), (error) => error.message.includes(`"static/lab/${escaped}lab.js"`), escaped),
    );
  }
});

test('the public registry projects a v5 surface in the v4 shape, without navigation detail or built assets', async () => {
  const v5 = await readManifest(essV5);
  const [declared] = buildRegistry([v5]).surfaces;
  assert.equal('builtAssets' in declared, false);
  assert.deepEqual(declared.source.navigation, {group: 'Foundation', label: 'ESS', order: 30});

  const enumV5 = structuredClone(v5);
  enumV5.surfaces[0].source.navigation = {group: 'Foundation', label: 'ESS', order: 30, sidebar: 'autogenerated', landing: 'docs/index.md', menuWithheld: ['docs/guides/record-realization.md']};
  const v4 = structuredClone(enumV5);
  v4.schema = 'b10x-docs/v4';
  delete v4.surfaces[0].builtAssets;
  v4.surfaces[0].source.navigation = {group: 'Foundation', label: 'ESS', order: 30, sidebar: 'autogenerated'};
  assert.deepEqual(buildRegistry([enumV5]).surfaces, buildRegistry([v4]).surfaces);
});

test('every earlier manifest revision remains accepted beside v5', async () => {
  const schemas = [];
  for (const fixture of ['public.yaml', 'public-v2.yaml', 'public-v3.yaml', 'public-v4.yaml', 'ess-v5.yaml']) {
    schemas.push((await readDocument(new URL(`../fixtures/${fixture}`, import.meta.url))).schema);
  }
  assert.deepEqual(schemas, ['b10x-docs/v1', 'b10x-docs/v2', 'b10x-docs/v3', 'b10x-docs/v4', 'b10x-docs/v5']);
  const v4 = await fs.readFile(new URL('../schema/b10x.docs.v4.schema.json', import.meta.url));
  assert.equal(createHash('sha256').update(v4).digest('hex'), V4_SCHEMA_SHA256);
  const v5 = await import('@beyond10x/docs-system/schema/v5', {with: {type: 'json'}});
  assert.equal(v5.default.properties.schema.const, 'b10x-docs/v5');
});

test('public registry dual-reads v1 and v2 deterministically', async () => {
  const v1 = await readManifest(new URL('../fixtures/public.yaml', import.meta.url));
  const v2 = await readManifest(new URL('../fixtures/public-v2.yaml', import.meta.url));
  v1.surfaces.push({...v1.surfaces[0], id: 'internal', canonicalUrl: 'https://service.invalid/docs/', availability: 'local-only', discoverability: 'internal'});
  const registry = buildRegistry([v2, v1]);
  assert.equal(registry.schema, 'b10x-docs-registry/v2');
  assert.deepEqual(registry.surfaces.map((surface) => surface.key), ['agentplugins/docs', 'getting-started/docs']);
  assert.equal(registry.surfaces[0].adoption.mode, 'install');
});

test('a public relationship to an unavailable surface is refused', async () => {
  const manifest = await readManifest(new URL('../fixtures/public.yaml', import.meta.url));
  manifest.surfaces[0].relationships = [{target: 'private/docs', kind: 'uses'}];
  assert.throws(() => buildRegistry([manifest]), /non-public surface private\/docs/);
});

test('ledger enriches releases and validates public relationships', async () => {
  const manifests = await Promise.all([
    readManifest(new URL('../fixtures/public.yaml', import.meta.url)),
    readManifest(new URL('../fixtures/public-v2.yaml', import.meta.url)),
  ]);
  const change = await readChange(new URL('../fixtures/change.yaml', import.meta.url));
  const ledger = buildLedger(buildRegistry(manifests), [change], {
    schema: 'b10x-release-facts/v1',
    releases: [
      {repository: 'agentplugins', version: '0.3.1', publishedAt: '2026-09-01T12:00:00Z', url: 'https://github.com/beyond10x/agentplugins/releases/tag/0.3.1'},
      {repository: 'getting-started', version: '0.1.0', publishedAt: '2026-08-31T12:00:00Z', url: 'https://github.com/beyond10x/getting-started/releases/tag/0.1.0'},
      {repository: 'private', version: '9.9.9', publishedAt: '2026-09-02T12:00:00Z', url: 'https://example.invalid/private'},
    ],
  });
  assert.deepEqual(ledger.changes.map((entry) => entry.key), ['agentplugins/0.3.1', 'getting-started/0.1.0']);
  assert.equal(ledger.changes[0].automatic, false);
  assert.equal(ledger.changes[1].automatic, true);
});

test('change relations cannot expose unknown public state', async () => {
  const manifests = await Promise.all([
    readManifest(new URL('../fixtures/public.yaml', import.meta.url)),
    readManifest(new URL('../fixtures/public-v2.yaml', import.meta.url)),
  ]);
  const change = await readChange(new URL('../fixtures/change.yaml', import.meta.url));
  change.relations = [{target: 'change:aep/missing', kind: 'depends-on'}];
  assert.throws(() => buildLedger(buildRegistry(manifests), [change]), /unknown change aep\/missing/);
});

test('feeds are stable derivatives of the ledger', async () => {
  const manifests = await Promise.all([
    readManifest(new URL('../fixtures/public.yaml', import.meta.url)),
    readManifest(new URL('../fixtures/public-v2.yaml', import.meta.url)),
  ]);
  const change = await readChange(new URL('../fixtures/change.yaml', import.meta.url));
  const ledger = buildLedger(buildRegistry(manifests), [change]);
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'b10x-docs-system-'));
  const rss = path.join(directory, 'feed.xml');
  const json = path.join(directory, 'feed.json');

  await writeRss(rss, ledger);
  await writeJsonFeed(json, ledger);
  const first = await Promise.all([fs.readFile(rss, 'utf8'), fs.readFile(json, 'utf8')]);
  await writeRss(rss, ledger);
  await writeJsonFeed(json, ledger);
  const second = await Promise.all([fs.readFile(rss, 'utf8'), fs.readFile(json, 'utf8')]);

  assert.deepEqual(second, first);
  assert.match(first[0], /<guid isPermaLink="false">agentplugins\/0.3.1<\/guid>/);
  assert.equal(JSON.parse(first[1]).items[0].id, 'agentplugins/0.3.1');
  await fs.rm(directory, {recursive: true});
});
