import {Children, isValidElement, useEffect, useId, useMemo, useRef, useState} from 'react';
import type {CSSProperties, ReactNode} from 'react';
import Link from '@docusaurus/Link';
import useBrokenLinks from '@docusaurus/useBrokenLinks';
import CodeBlock from '@theme/CodeBlock';
import {DomainGraph, ProtocolGraph} from './charts.js';
import {StatusBadge, StatusGlyph, Truth} from './components.js';
import type {ProtocolKindName} from './components.js';
import {buildHref, buildLabel, FAMILY, familyMembers, isFamilyRelatedTool, relationPhrase} from './family.js';
import type {DocsSystemBuild} from './family.js';
import type {ProductId} from './product-palette.js';
import {landingKpis, parseCaseDocument, parseCodePairDocument, parseStatusDocument, parseTerminalSession, parseTranscript} from './product-data.js';
import type {
  ProductAction,
  ProductArt,
  ProductFeature,
  ProductFlowStep,
  ProductLandingData,
  ProductLandingSection,
  ProductStatus,
  ProductStatusItem,
  RelatedToolEntry,
  ResolvedKpi,
  StatusDocumentItem,
  TerminalEntry,
  TerminalSession,
  TerminalTone,
} from './product-data.js';

export {StatusBadge};

// ---------------------------------------------------------------------------------------------
// Terminal
// ---------------------------------------------------------------------------------------------

export interface TerminalProps {
  /** A recorded `b10x-terminal/1` session, typically generated by the repository. */
  session?: TerminalSession | unknown;
  /** A verbatim transcript: `$ ` starts a command, `# ` a comment before a command. */
  transcript?: string;
  /** The same as `transcript`, for MDX children. */
  children?: ReactNode;
  title?: string;
  /** Footer line; defaults to the session's provenance. */
  caption?: ReactNode;
  /** Type the commands out once the terminal is visible. Off by default; reduced motion disables it. */
  animate?: boolean;
  prompt?: string;
  /** The hero's slight tilt. */
  tilt?: boolean;
}

export function Terminal({session, transcript, children, title, caption, animate = false, prompt = '$', tilt = false}: TerminalProps): ReactNode {
  const resolved = useMemo(() => {
    if (session !== undefined) {
      const parsed = parseTerminalSession(session);
      return {entries: parsed.entries, title: parsed.title, provenance: parsed.recordedWith, tones: parsed.tones};
    }
    const text = transcript ?? (typeof children === 'string' ? children : Children.toArray(children).filter((child) => typeof child === 'string').join(''));
    if (!text.trim()) throw new Error('Terminal requires a session, a transcript, or transcript children');
    return {entries: parseTranscript(text), title: undefined, provenance: undefined, tones: undefined};
  }, [session, transcript, children]);
  const label = title ?? resolved.title ?? 'Terminal';
  const footer = caption ?? resolved.provenance;
  const gutter = resolved.entries.some((entry) => entry.exitCode !== undefined);
  const summary = terminalSummary(resolved.entries, resolved.tones);
  const commands = resolved.entries.map((entry) => entry.command).join('\n');
  const figure = useRef<HTMLElement>(null);
  const progress = useTyping(resolved.entries, animate, figure);
  const [copied, setCopied] = useState(false);
  const statusId = `b10x-terminal-${useId().replaceAll(':', '')}-status`;
  const copy = async (): Promise<void> => {
    try {
      await navigator.clipboard.writeText(commands);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1800);
    } catch {
      setCopied(false);
    }
  };
  return <figure ref={figure} className={['b10x-terminal', tilt && 'b10x-terminal--tilt', gutter && 'b10x-terminal--gutter'].filter(Boolean).join(' ')} aria-label={label}>
    <div className="b10x-terminal__bar">
      <span className="b10x-terminal__lights" aria-hidden="true"><i /><i /><i /></span>
      <span className="b10x-terminal__title">{label}</span>
      <button type="button" className="b10x-terminal__copy" onClick={copy} aria-describedby={statusId}>{copied ? 'Copied' : 'Copy commands'}</button>
      <span className="b10x-sr-only" role="status" id={statusId}>{copied ? 'Commands copied to the clipboard' : ''}</span>
    </div>
    <pre className="b10x-terminal__body" tabIndex={0}><code>{resolved.entries.map((entry, index) => <TerminalLines key={index} entry={entry} prompt={prompt} shown={progress?.[index]} last={index === resolved.entries.length - 1} gutter={gutter} tones={resolved.tones} />)}</code></pre>
    {(footer || summary) && <figcaption className="b10x-terminal__foot">{footer && <><span className="b10x-terminal__dot" aria-hidden="true" /><span className="b10x-terminal__provenance">{footer}</span></>}{summary && <span className="b10x-terminal__summary">{summary}</span>}</figcaption>}
  </figure>;
}

function TerminalLines({entry, prompt, shown, last, gutter, tones}: {entry: TerminalEntry; prompt: string; shown?: {command: number; output: boolean}; last: boolean; gutter: boolean; tones?: Record<string, TerminalTone>}): ReactNode {
  const typed = shown ? entry.command.slice(0, shown.command) : entry.command;
  const rest = shown ? entry.command.slice(shown.command) : '';
  const outputVisible = !shown || shown.output;
  const failed = entry.exitCode !== undefined && entry.exitCode !== 0;
  const blank = gutter ? <span className="b10x-terminal__gutter" aria-hidden="true"> </span> : null;
  const exit = entry.exitCode === undefined ? blank : <span className={`b10x-terminal__gutter b10x-terminal__gutter--${failed ? 'failed' : 'passed'}`} title={`exit ${entry.exitCode}`} aria-hidden="true">{failed ? '✕' : '✓'}</span>;
  const json = /^\s*[[{]/.test(entry.output ?? '');
  return <>
    {entry.comment && <span className="b10x-terminal__comment">{blank}# {entry.comment}{'\n'}</span>}
    <span className="b10x-terminal__line">{exit}<span className="b10x-terminal__prompt" aria-hidden="true">{prompt} </span><span className="b10x-terminal__command">{typed}<span className="b10x-terminal__pending">{rest}</span></span>{'\n'}</span>
    {entry.output !== undefined && entry.output !== '' && <span className={['b10x-terminal__output', failed && 'b10x-terminal__output--failed', !outputVisible && 'b10x-terminal__pending'].filter(Boolean).join(' ')}>{entry.output.split('\n').map((line, index) => <span key={index}>{blank}{toneLine(line, tones, json)}{'\n'}</span>)}</span>}
    {!last && '\n'}
  </>;
}

/** Colour recorded output: the session's tone words first, then JSON tokens when the output is JSON. */
export function toneLine(line: string, tones: Record<string, TerminalTone> | undefined, json: boolean): ReactNode[] {
  const words = Object.keys(tones ?? {}).sort((left, right) => right.length - left.length);
  const pattern = words.length ? new RegExp(words.map((word) => word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|'), 'g') : undefined;
  const parts: ReactNode[] = [];
  let cursor = 0;
  const plain = (text: string): void => { if (text) parts.push(...(json ? jsonTokens(text, parts.length) : [text])); };
  if (pattern) {
    for (const match of line.matchAll(pattern)) {
      plain(line.slice(cursor, match.index));
      parts.push(<span key={`t${parts.length}`} className={`b10x-terminal__tone b10x-terminal__tone--${tones![match[0]]}`}>{match[0]}</span>);
      cursor = match.index! + match[0].length;
    }
  }
  plain(line.slice(cursor));
  return parts;
}

function jsonTokens(text: string, offset: number): ReactNode[] {
  const parts: ReactNode[] = [];
  const token = /("(?:\\.|[^"\\])*")(\s*:)?|\b(true|false|null)\b|-?\b\d+(?:\.\d+)?(?:[eE][+-]?\d+)?\b|[{}[\],:]/g;
  let cursor = 0;
  for (const match of text.matchAll(token)) {
    if (match.index! > cursor) parts.push(text.slice(cursor, match.index));
    const kind = match[1] !== undefined ? (match[2] !== undefined ? 'key' : 'string') : match[3] !== undefined ? 'literal' : /^[-\d]/.test(match[0]) ? 'literal' : 'punctuation';
    if (kind === 'key') {
      parts.push(<span key={`j${offset}-${parts.length}`} className="b10x-terminal__json--key">{match[1]}</span>, <span key={`j${offset}-${parts.length + 1}`} className="b10x-terminal__json--punctuation">{match[2]}</span>);
    } else parts.push(<span key={`j${offset}-${parts.length}`} className={`b10x-terminal__json--${kind}`}>{match[0]}</span>);
    cursor = match.index! + match[0].length;
  }
  if (cursor < text.length) parts.push(text.slice(cursor));
  return parts;
}

/** "3/3 exit 0 · 6 ✓ · 0 ✕": exits from the recording, tone counts from its tone words. */
export function terminalSummary(entries: readonly TerminalEntry[], tones?: Record<string, TerminalTone>): string | undefined {
  const recorded = entries.filter((entry) => entry.exitCode !== undefined);
  if (!recorded.length) return undefined;
  const clean = recorded.filter((entry) => entry.exitCode === 0).length;
  const parts = [`${clean}/${recorded.length} exit 0`];
  if (tones && Object.keys(tones).length) {
    const count = (tone: TerminalTone): number => Object.entries(tones).filter(([, value]) => value === tone).reduce((sum, [word]) => sum + entries.reduce((total, entry) => total + ((entry.output ?? '').split(word).length - 1), 0), 0);
    parts.push(`${count('true')} ✓`, `${count('false')} ✕`);
  }
  return parts.join(' · ');
}

/** Type the commands once, when the terminal first scrolls into view; the full text is shown until then. */
function useTyping(entries: readonly TerminalEntry[], enabled: boolean, element: {current: HTMLElement | null}): Array<{command: number; output: boolean}> | undefined {
  const [state, setState] = useState<Array<{command: number; output: boolean}> | undefined>(undefined);
  const started = useRef(false);
  useEffect(() => {
    if (!enabled || started.current || typeof window === 'undefined') return;
    if (window.matchMedia?.('(prefers-reduced-motion: reduce)').matches) return;
    let frame = 0;
    const run = (): void => {
      started.current = true;
      const schedule: Array<{entry: number; at: number; chars: number; output: boolean}> = [];
      let time = 300;
      entries.forEach((entry, index) => {
        for (let chars = 1; chars <= entry.command.length; chars += 1) schedule.push({entry: index, at: (time += 28), chars, output: false});
        schedule.push({entry: index, at: (time += 260), chars: entry.command.length, output: true});
        time += 420;
      });
      setState(entries.map(() => ({command: 0, output: false})));
      const begin = performance.now();
      const tick = (now: number): void => {
        const elapsed = now - begin;
        const next = entries.map(() => ({command: 0, output: false}));
        for (const step of schedule) {
          if (step.at > elapsed) break;
          next[step.entry] = {command: step.chars, output: step.output};
        }
        setState(next);
        if (elapsed <= time) frame = window.requestAnimationFrame(tick);
        else setState(undefined);
      };
      frame = window.requestAnimationFrame(tick);
    };
    const target = element.current;
    if (!target || !('IntersectionObserver' in window)) { run(); return () => window.cancelAnimationFrame(frame); }
    const observer = new IntersectionObserver((records) => {
      if (records.some((record) => record.isIntersecting) && !started.current) { observer.disconnect(); run(); }
    }, {threshold: 0.6});
    observer.observe(target);
    return () => { observer.disconnect(); window.cancelAnimationFrame(frame); };
  }, [enabled, entries, element]);
  return state;
}

// ---------------------------------------------------------------------------------------------
// Feature grid, flow, status, related tools
// ---------------------------------------------------------------------------------------------

export interface FeatureProps extends Omit<ProductFeature, 'description'> {
  description?: string;
  children?: ReactNode;
}

/** One card of a `FeatureGrid`, for MDX authors who prefer children to an `items` array. */
export function Feature({title, description, href, status, icon, children}: FeatureProps): ReactNode {
  return <li className={['b10x-feature', icon && 'b10x-feature--icon'].filter(Boolean).join(' ')}>
    {icon && <KindIcon kind={icon} />}
    <h3>{href ? <Link to={href}>{title}</Link> : title}</h3>
    {status && <StatusBadge status={status} />}
    {description && <p>{description}</p>}
    {children && <div className="b10x-feature__body">{children}</div>}
  </li>;
}

/** A protocol kind's glyph as a 16 px icon in the kind colour (the same glyph as kind chips and legends). */
export function KindIcon({kind, label}: {kind: ProtocolKindName; label?: string}): ReactNode {
  return <span className={`b10x-kind-icon b10x-kind-icon--${kind}`} role={label ? 'img' : undefined} aria-label={label} aria-hidden={label ? undefined : true} />;
}

export interface FeatureGridProps {
  items?: readonly ProductFeature[];
  children?: ReactNode;
  /** Defaults from the number of cards: 4 → 2 × 2, 7–8 → 4 columns, otherwise up to 3. */
  columns?: 2 | 3 | 4;
  label?: string;
}

/** Columns that leave no orphan row for common counts. */
export function featureColumns(count: number): 2 | 3 | 4 {
  if (count === 4 || count <= 2) return 2;
  if (count === 7 || count === 8) return 4;
  return 3;
}

export function FeatureGrid({items, children, columns, label = 'What it does'}: FeatureGridProps): ReactNode {
  const count = (items?.length ?? 0) + Children.toArray(children).filter(isValidElement).length;
  const resolved = columns ?? featureColumns(count);
  return <ol className={`b10x-feature-grid b10x-feature-grid--${resolved}`} aria-label={label}>
    {items?.map((item) => <Feature key={item.title} {...item} />)}
    {children}
  </ol>;
}

export interface FlowStepProps extends ProductFlowStep {children?: ReactNode}

export function FlowStep({label, title, description, children}: FlowStepProps): ReactNode {
  return <li className="b10x-flow__step">
    {label && <span className="b10x-flow__label">{label}</span>}
    <strong>{title}</strong>
    {description && <p>{description}</p>}
    {children}
  </li>;
}

export interface FlowProps {
  steps?: readonly ProductFlowStep[];
  children?: ReactNode;
  label?: string;
}

/** Steps with arrows between them; wraps to a vertical sequence on narrow screens. */
export function Flow({steps, children, label = 'How it works'}: FlowProps): ReactNode {
  const count = (steps?.length ?? 0) + Children.toArray(children).filter(isValidElement).length;
  return <ol className="b10x-flow" aria-label={label} style={{'--b10x-flow-count': count} as CSSProperties}>
    {steps?.map((step) => <FlowStep key={step.title} {...step} />)}
    {children}
  </ol>;
}

const STATUS_ORDER: readonly ProductStatus[] = ['shipped', 'decided', 'planned'];
const STATUS_LABELS: Record<ProductStatus, string> = {shipped: 'Shipped', decided: 'Decided', planned: 'Planned'};

export interface StatusStripProps {
  items: readonly ProductStatusItem[];
  label?: string;
  /** Captions above each group; the defaults state what each status means. */
  groupLabels?: Partial<Record<ProductStatus, string>>;
  /** Provenance of a `b10x-status/1` file: when it was checked and what produced it. */
  asOf?: string;
  source?: string;
}

const STATUS_GROUP_LABELS: Record<ProductStatus, string> = {shipped: 'Shipped · runs today', decided: 'Decided · recorded, not built', planned: 'Planned · roadmap only'};

function statusGroups<T extends ProductStatusItem>(items: readonly T[]): Array<{status: ProductStatus; items: T[]}> {
  return STATUS_ORDER.map((status) => ({status, items: items.filter((item) => item.status === status)})).filter((group) => group.items.length > 0);
}

/** The proportion bar and its legend: counts per status, glyph and word beside every colour. */
export function StatusSummary({items}: {items: readonly ProductStatusItem[]}): ReactNode {
  const groups = statusGroups(items);
  const summary = groups.map(({status, items: members}) => `${members.length} ${STATUS_LABELS[status].toLowerCase()}`).join(', ');
  return <>
    <div className="b10x-status-strip__bar" role="img" aria-label={`${items.length} capabilities: ${summary}`}>
      {groups.map(({status, items: members}) => <span key={status} className={`b10x-status-strip__segment b10x-status-strip__segment--${status}`} style={{flexGrow: members.length} as CSSProperties} />)}
    </div>
    <ul className="b10x-status-strip__legend" aria-hidden="true">
      {groups.map(({status, items: members}) => <li key={status}><StatusBadge status={status} /><strong>{members.length}</strong></li>)}
    </ul>
  </>;
}

function StatusProvenance({asOf, source}: {asOf?: string; source?: string}): ReactNode {
  if (!asOf && !source) return null;
  return <p className="b10x-status-strip__source">{[asOf && `As of ${asOf}`, source].filter(Boolean).join(' · ')}</p>;
}

/** What exists today and what does not, counted from the items themselves and grouped by state. */
export function StatusStrip({items, label = 'Status', groupLabels = {}, asOf, source}: StatusStripProps): ReactNode {
  const groups = statusGroups(items);
  return <section className="b10x-status-strip" aria-label={label}>
    <StatusSummary items={items} />
    {groups.map(({status, items: members}) => <div className={`b10x-status-strip__group b10x-status-strip__group--${status}`} key={status}>
      <p className="b10x-status-strip__group-title">{groupLabels[status] ?? STATUS_GROUP_LABELS[status]}</p>
      <ul className="b10x-status-strip__items">
        {members.map((item) => <li key={item.label}>
          <StatusBadge status={item.status} />
          <span className="b10x-status-strip__label">{item.href ? <Link to={item.href}>{item.label}</Link> : item.label}</span>
          {item.detail && <span className="b10x-status-strip__detail">{item.detail}</span>}
        </li>)}
      </ul>
    </div>)}
    <StatusProvenance asOf={asOf} source={source} />
  </section>;
}

export interface StatusTableProps {
  /** A `b10x-status/1` document, imported from the same file the landing's status section reads. */
  data: unknown;
  label?: string;
  /** Show only these statuses. */
  only?: readonly ProductStatus[];
}

/**
 * The status page table: every item with its badge and detail, grouped by area when the file has
 * areas, under the same proportion bar as the landing strip.
 */
export function StatusTable({data, label = 'Status of every capability', only}: StatusTableProps): ReactNode {
  const parsed = useMemo(() => {
    try {
      return {document: parseStatusDocument(data)};
    } catch (error) {
      return {error: error instanceof Error ? error.message : String(error)};
    }
  }, [data]);
  if ('error' in parsed) return <aside className="b10x-callout b10x-callout--danger" role="alert"><p className="b10x-callout__title b10x-eyebrow">Cannot render status table</p><div className="b10x-callout__content"><p><code>{parsed.error}</code></p></div></aside>;
  const items = parsed.document!.items.filter((item) => !only || only.includes(item.status));
  // Array.from, not a spread: the site's loose Babel transform turns a spread Set into [Set].
  const areas = Array.from(new Set(items.map((item) => item.area ?? '')));
  const grouped = areas.some(Boolean);
  const row = (item: StatusDocumentItem): ReactNode => <tr key={item.label}>
    <th scope="row">{item.href ? <Link to={item.href}>{item.label}</Link> : item.label}</th>
    <td><StatusBadge status={item.status} /></td>
    <td>{item.detail ?? '—'}</td>
  </tr>;
  return <section className="b10x-status-table" aria-label={label}>
    <StatusSummary items={items} />
    <div className="b10x-table-wrap"><table>
      <thead><tr><th scope="col">Capability</th><th scope="col">Status</th><th scope="col">Detail</th></tr></thead>
      {grouped
        ? areas.map((area) => <tbody key={area || 'other'}>
          <tr className="b10x-status-table__area"><th scope="rowgroup" colSpan={3}>{area || 'Other'}</th></tr>
          {items.filter((item) => (item.area ?? '') === area).map(row)}
        </tbody>)
        : <tbody>{items.map(row)}</tbody>}
    </table></div>
    <StatusProvenance asOf={parsed.document!.asOf} source={parsed.document!.source} />
  </section>;
}

export interface RelatedToolsProps {
  /** Tools written out in full, or `{id, relation}` entries resolved from the family registry. */
  tools: readonly RelatedToolEntry[];
  label?: string;
  /** The product whose site this is; completes the relation phrase ("uses Canon"). */
  current?: ProductId;
}

export function RelatedTools({tools, label = 'Related tools', current}: RelatedToolsProps): ReactNode {
  return <ul className="b10x-related" aria-label={label}>
    {tools.map((tool) => {
      if (isFamilyRelatedTool(tool)) {
        const member = FAMILY[tool.id];
        if (!member) throw new Error(`RelatedTools: unknown family id ${JSON.stringify(tool.id)}`);
        return <li key={member.id}>
          <Link className={`b10x-related__card b10x-related__card--family b10x-family--${member.id}`} to={member.url}>
            <span className="b10x-mark b10x-mark--family" aria-hidden="true">{member.mark}</span>
            <span className="b10x-related__copy">
              <strong>{member.name}</strong>
              <span>{member.description}</span>
              <span className="b10x-related__relation">{relationPhrase(tool.relation, current)}{tool.via && <> <span aria-hidden="true">→</span> {tool.via}</>}</span>
            </span>
            <span className="b10x-related__arrow" aria-hidden="true">→</span>
          </Link>
        </li>;
      }
      return <li key={tool.name}>
        <Link className="b10x-related__card" to={tool.href}>
          <span className="b10x-mark" aria-hidden="true">{tool.mark ?? tool.name.slice(0, 1)}</span>
          <span className="b10x-related__copy">
            <strong>{tool.name}</strong>
            <span>{tool.description}</span>
          </span>
          {tool.status && <StatusBadge status={tool.status} />}
          <span className="b10x-related__arrow" aria-hidden="true">→</span>
        </Link>
      </li>;
    })}
  </ul>;
}

/** Every family product as a chip, the current one highlighted. Rendered in the product-site footer. */
export function FamilyStrip({current, label = 'beyond10x tools'}: {current?: ProductId; label?: string}): ReactNode {
  return <nav className="b10x-family-strip" aria-label={label}>
    <p className="b10x-family-strip__label" aria-hidden="true">{label}</p>
    <ul>
      {familyMembers().map((member) => <li key={member.id}>
        <a className={['b10x-family-chip', `b10x-family--${member.id}`, member.id === current && 'is-current'].filter(Boolean).join(' ')} href={member.url} aria-current={member.id === current ? 'true' : undefined} title={member.tagline}>
          <span className="b10x-mark b10x-mark--family b10x-mark--small" aria-hidden="true">{member.mark}</span>
          {member.name}
          {member.id === current && <span className="b10x-sr-only"> (this site)</span>}
        </a>
      </li>)}
    </ul>
  </nav>;
}

/** "This build: docs-system 929f965", linked to the commit when it is one. */
export function BuildLine({build}: {build: DocsSystemBuild}): ReactNode {
  const href = buildHref(build);
  return <p className="b10x-build-line"><span className="b10x-build-line__label">This build</span>{href ? <a href={href}>{buildLabel(build)}</a> : <span>{buildLabel(build)}</span>}</p>;
}

/** The navbar product switcher: a disclosure next to the wordmark listing the family. */
export function ProductSwitcher({current}: {current: ProductId}): ReactNode {
  const ref = useRef<HTMLDetailsElement>(null);
  useEffect(() => {
    const close = (event: Event): void => {
      const element = ref.current;
      if (!element?.open) return;
      if (event instanceof KeyboardEvent ? event.key === 'Escape' : !element.contains(event.target as Node)) {
        element.open = false;
        if (event instanceof KeyboardEvent) element.querySelector('summary')?.focus();
      }
    };
    document.addEventListener('pointerdown', close);
    document.addEventListener('keydown', close);
    return () => { document.removeEventListener('pointerdown', close); document.removeEventListener('keydown', close); };
  }, []);
  return <details className="b10x-product-switcher" ref={ref}>
    <summary className="b10x-product-switcher__toggle" aria-label="Switch to another beyond10x tool">
      <svg viewBox="0 0 12 12" aria-hidden="true"><path d="M3 4.5 6 7.5 9 4.5" /></svg>
    </summary>
    <ul className="b10x-product-switcher__panel">
      {familyMembers().map((member) => <li key={member.id}>
        <a className={['b10x-product-switcher__item', `b10x-family--${member.id}`, member.id === current && 'is-current'].filter(Boolean).join(' ')} href={member.url} aria-current={member.id === current ? 'true' : undefined}>
          <span className="b10x-mark b10x-mark--family" aria-hidden="true">{member.mark}</span>
          <span className="b10x-product-switcher__copy"><strong>{member.name}</strong><span>{member.tagline}</span></span>
          {member.id === current && <span className="b10x-product-switcher__here">You are here</span>}
        </a>
      </li>)}
    </ul>
  </details>;
}

// ---------------------------------------------------------------------------------------------
// Landing page
// ---------------------------------------------------------------------------------------------

export interface ProductHeroProps {
  eyebrow?: ReactNode;
  /** One entry per line; the last line is emphasised. */
  promise: readonly string[];
  lede: ReactNode;
  actions?: readonly ProductAction[];
  meta?: ReactNode;
  aside?: ReactNode;
  /** The KPI row under the hero, spanning both columns. */
  kpis?: readonly ResolvedKpi[];
  /** Element id of the heading; change it when a page shows more than one hero. */
  titleId?: string;
}

export function ProductHero({eyebrow, promise, lede, actions = [], meta, aside, kpis, titleId = 'b10x-hero-title'}: ProductHeroProps): ReactNode {
  const lines = promise.length > 1 ? promise.slice(0, -1) : [];
  const emphasis = promise[promise.length - 1];
  return <section className={['b10x-hero', aside ? '' : 'b10x-hero--solo'].filter(Boolean).join(' ')} aria-labelledby={titleId}>
    <div className="b10x-hero__copy">
      {eyebrow && <p className="b10x-kicker"><span className="b10x-kicker__dot" aria-hidden="true" />{eyebrow}</p>}
      <h1 id={titleId}>{lines.map((line) => <span key={line}>{line}<br /></span>)}<em>{emphasis}</em></h1>
      <p className="b10x-hero__lede">{lede}</p>
      {actions.length > 0 && <div className="b10x-hero__actions">{actions.map((action) => <Link key={action.href} to={action.href} className={action.kind === 'primary' ? 'b10x-button' : 'b10x-text-link'}>{action.label} <span aria-hidden="true">{action.kind === 'primary' ? '→' : action.href.startsWith('#') ? '↓' : '→'}</span></Link>)}</div>}
      {meta && <p className="b10x-hero__meta">{meta}</p>}
    </div>
    {aside && <div className="b10x-hero__aside">{aside}</div>}
    {kpis && kpis.length > 0 && <KpiRow items={kpis} />}
  </section>;
}

/** Numbered KPI tiles. Values are counted from data (see `landingKpis`), never typed. */
export function KpiRow({items, label = 'Key figures'}: {items: readonly ResolvedKpi[]; label?: string}): ReactNode {
  return <dl className="b10x-kpis" aria-label={label} style={{'--b10x-kpi-count': items.length} as CSSProperties}>
    {items.map((item, index) => <div key={`${item.count}-${index}`} className={`b10x-kpi b10x-kpi--${item.tone}`}>
      <dt className="b10x-kpi__label"><span className="b10x-kpi__index" aria-hidden="true">{String(index + 1).padStart(2, '0')}</span>{item.tone !== 'product' && <StatusGlyph status={item.tone} className="b10x-kpi__glyph" />}{item.label}</dt>
      <dd className="b10x-kpi__value">{item.value}</dd>
    </div>)}
  </dl>;
}

/** The hero aside drawn from the product's own data. */
export function HeroArt({art}: {art: ProductArt}): ReactNode {
  const body = (() => {
    switch (art.kind) {
      case 'terminal': return <Terminal session={art.session} tilt animate caption={art.caption} />;
      case 'protocol-graph': return <ProtocolGraph data={art.data} variant="hero" caption={art.caption} />;
      case 'domain-graph': return <DomainGraph data={art.data} variant="hero" caption={art.caption} />;
      case 'case': return <CaseCard data={art.data} caption={art.caption} />;
      case 'code-pair': return <CodePair data={art.data} caption={art.caption} />;
      default: return null;
    }
  })();
  return <div className={`b10x-hero-art b10x-hero-art--${art.kind}`}>{body}</div>;
}

function DataError({kind, message}: {kind: string; message: string}): ReactNode {
  return <aside className="b10x-callout b10x-callout--danger" role="alert"><p className="b10x-callout__title b10x-eyebrow">Cannot render {kind}</p><div className="b10x-callout__content"><p><code>{message}</code></p></div></aside>;
}

function useParsed<T>(data: unknown, parse: (value: unknown) => T): {value: T} | {error: string} {
  return useMemo(() => {
    try {
      return {value: parse(data)};
    } catch (error) {
      return {error: error instanceof Error ? error.message : String(error)};
    }
  }, [data, parse]);
}

const STATE_GLYPHS: Record<string, string> = {blocked: '⊘', legitimate: '✓', admissible: '○', inadmissible: '⊘', earned: '✓'};

/**
 * A case evaluated more than once, frame by frame: claims as truth chips, outcome and action states
 * as neutral outlined chips (they are not truth values). From a `b10x-case/1` recording.
 */
export function CaseCard({data, caption}: {data: unknown; caption?: ReactNode}): ReactNode {
  const parsed = useParsed(data, parseCaseDocument);
  if ('error' in parsed) return <DataError kind="case card" message={parsed.error} />;
  const document = parsed.value;
  return <figure className="b10x-case" aria-label={`Case ${document.case}${document.protocol ? ` under ${document.protocol}` : ''}`}>
    <p className="b10x-case__kicker">Case <code>{document.case}</code>{document.protocol && <> · <code>{document.protocol}</code></>}</p>
    <ol className="b10x-case__frames" style={{'--b10x-case-frames': document.frames.length} as CSSProperties}>
      {document.frames.map((frame, index) => <li key={`${frame.label}-${index}`} className={['b10x-case__frame', frame.current && 'is-current'].filter(Boolean).join(' ')}>
        <p className="b10x-case__label">{frame.label}{frame.current && <span className="b10x-case__current"> · current</span>}</p>
        <ul className="b10x-case__rows">
          {frame.claims?.map((claim) => <li key={`c-${claim.name}`}><code>{claim.name}</code><Truth value={claim.value} /></li>)}
          {frame.outcomes?.map((outcome) => <li key={`o-${outcome.name}`}><code>{outcome.name}</code><span className="b10x-chip b10x-chip--state"><span className="b10x-chip__glyph" aria-hidden="true">{STATE_GLYPHS[outcome.state] ?? '·'}</span><span className="b10x-chip__text">{outcome.state}</span></span></li>)}
          {frame.actions?.map((action) => <li key={`a-${action.name}`}><code>{action.name}</code><span className="b10x-chip b10x-chip--state"><span className="b10x-chip__glyph" aria-hidden="true">{STATE_GLYPHS[action.state] ?? '·'}</span><span className="b10x-chip__text">{action.state}</span></span></li>)}
        </ul>
        {frame.notes?.map((note) => <p key={note} className="b10x-case__note">{note}</p>)}
      </li>)}
    </ol>
    {caption && <figcaption className="b10x-case__caption">{caption}</figcaption>}
    {document.recordedWith && <p className="b10x-case__source">{document.recordedWith}</p>}
  </figure>;
}

/** A source and what was generated from it, from a `b10x-code-pair/1` document. */
export function CodePair({data, caption}: {data: unknown; caption?: ReactNode}): ReactNode {
  const parsed = useParsed(data, parseCodePairDocument);
  if ('error' in parsed) return <DataError kind="code pair" message={parsed.error} />;
  const document = parsed.value;
  return <figure className="b10x-code-pair">
    <div className="b10x-code-pair__panes">
      <div className="b10x-code-pair__pane"><CodeBlock language={document.from.language} title={document.from.title}>{document.from.code.replace(/\s+$/, '')}</CodeBlock></div>
      <p className="b10x-code-pair__via"><span className="b10x-code-pair__arrow" aria-hidden="true" />{document.via ? <code>{document.via}</code> : <span>generates</span>}</p>
      <div className="b10x-code-pair__pane"><CodeBlock language={document.to.language} title={document.to.title}>{document.to.code.replace(/\s+$/, '')}</CodeBlock></div>
    </div>
    {caption && <figcaption className="b10x-code-pair__caption">{caption}</figcaption>}
    {document.recordedWith && <p className="b10x-code-pair__source">{document.recordedWith}</p>}
  </figure>;
}

export interface ProductSectionProps {
  id?: string;
  /** Section number; renders as `01 / eyebrow`. */
  number?: number;
  eyebrow?: string;
  title: ReactNode;
  lede?: ReactNode;
  /** The section's content kind; graph and status sections sit on the alternate ground. */
  kind?: ProductLandingSection['kind'];
  children?: ReactNode;
}

export function ProductSection({id, number, eyebrow, title, lede, kind, children}: ProductSectionProps): ReactNode {
  // Register the anchor so Docusaurus link checking knows `#id` exists.
  const links = useBrokenLinks();
  if (id) links.collectAnchor(id);
  const titleId = id ? `${id}-title` : undefined;
  const kicker = [number !== undefined ? String(number).padStart(2, '0') : undefined, eyebrow].filter(Boolean).join(' / ');
  return <section className={['b10x-product-section', kind && `b10x-product-section--${kind}`].filter(Boolean).join(' ')} id={id} aria-labelledby={titleId}>
    <header className="b10x-product-section__header">
      {kicker && <p className="b10x-kicker">{kicker}</p>}
      <h2 id={titleId}>{title}</h2>
      {lede && <p className="b10x-product-section__lede">{lede}</p>}
    </header>
    {children}
  </section>;
}

/** The landing hero: art from `product.art` (or the older `product.terminal`) and the KPI row. */
export function LandingHero({data, titleId}: {data: ProductLandingData; titleId?: string}): ReactNode {
  const {product} = data;
  const art: ProductArt | undefined = product.art ?? (product.terminal !== undefined ? {kind: 'terminal', session: product.terminal, ...(product.terminalCaption ? {caption: product.terminalCaption} : {})} : undefined);
  const kpis = useMemo(() => landingKpis(data), [data]);
  return <ProductHero
    eyebrow={product.eyebrow}
    promise={product.promise}
    lede={product.lede}
    actions={product.actions}
    meta={product.meta}
    aside={art ? <HeroArt art={art} /> : undefined}
    kpis={kpis}
    titleId={titleId}
  />;
}

export function ProductLanding({data, current}: {data: ProductLandingData; current?: ProductId}): ReactNode {
  return <div className="b10x-product">
    <LandingHero data={data} />
    {data.sections.map((section, index) => <ProductSection key={`${section.kind}-${index}`} id={sectionId(data.sections, index)} number={index + 1} eyebrow={section.eyebrow} title={section.title} lede={section.lede} kind={section.kind}>
      <LandingSection section={section} current={current} />
    </ProductSection>)}
  </div>;
}

function LandingSection({section, current}: {section: ProductLandingSection; current?: ProductId}): ReactNode {
  switch (section.kind) {
    case 'features': return <FeatureGrid items={section.items} />;
    case 'flow': return <Flow steps={section.steps} />;
    case 'status': return typeof section.items === 'string' ? <DataError kind="status" message={`status file ${section.items} was not read; the product-site plugin reads it at build time`} /> : <StatusStrip items={section.items} asOf={section.asOf} source={section.source} />;
    case 'related': return <RelatedTools tools={section.tools} current={current} />;
    case 'terminal': return <Terminal session={section.session} />;
    case 'protocol-graph': return <ProtocolGraph data={section.data} caption={section.caption} />;
    case 'domain-graph': return <DomainGraph data={section.data} caption={section.caption} />;
    default: return null;
  }
}

const SECTION_IDS: Record<ProductLandingSection['kind'], string> = {features: 'what', flow: 'how', status: 'status', related: 'related', terminal: 'try', 'protocol-graph': 'protocol', 'domain-graph': 'domain'};

function sectionId(sections: readonly ProductLandingSection[], index: number): string {
  const base = SECTION_IDS[sections[index].kind];
  const earlier = sections.slice(0, index).filter((section) => section.kind === sections[index].kind).length;
  return earlier ? `${base}-${earlier + 1}` : base;
}

