import {Children, isValidElement, useEffect, useId, useMemo, useRef, useState} from 'react';
import type {CSSProperties, ReactNode} from 'react';
import Link from '@docusaurus/Link';
import useBrokenLinks from '@docusaurus/useBrokenLinks';
import {DomainGraph, ProtocolGraph} from './charts.js';
import {StatusBadge} from './components.js';
import {parseTerminalSession, parseTranscript} from './product-data.js';
import type {
  ProductAction,
  ProductFeature,
  ProductFlowStep,
  ProductLandingData,
  ProductLandingSection,
  ProductStatus,
  ProductStatusItem,
  RelatedTool,
  TerminalEntry,
  TerminalSession,
} from './product-data.js';

export {StatusBadge};

// ---------------------------------------------------------------------------------------------
// Terminal
// ---------------------------------------------------------------------------------------------

export interface TerminalProps {
  /** A recorded `b10x-terminal/1` session, typically generated by the repository. */
  session?: TerminalSession | unknown;
  /** A verbatim transcript: `$ ` starts a command, `# ` a comment before a command. */
  transcript?: string;
  /** The same as `transcript`, for MDX children. */
  children?: ReactNode;
  title?: string;
  /** Footer line; defaults to the session's provenance. */
  caption?: ReactNode;
  /** Type the commands out once the terminal is visible. Off by default; reduced motion disables it. */
  animate?: boolean;
  prompt?: string;
  /** The hero's slight tilt. */
  tilt?: boolean;
}

export function Terminal({session, transcript, children, title, caption, animate = false, prompt = '$', tilt = false}: TerminalProps): ReactNode {
  const resolved = useMemo(() => {
    if (session !== undefined) {
      const parsed = parseTerminalSession(session);
      return {entries: parsed.entries, title: parsed.title, provenance: parsed.recordedWith};
    }
    const text = transcript ?? (typeof children === 'string' ? children : Children.toArray(children).filter((child) => typeof child === 'string').join(''));
    if (!text.trim()) throw new Error('Terminal requires a session, a transcript, or transcript children');
    return {entries: parseTranscript(text), title: undefined, provenance: undefined};
  }, [session, transcript, children]);
  const label = title ?? resolved.title ?? 'Terminal';
  const footer = caption ?? resolved.provenance;
  const commands = resolved.entries.map((entry) => entry.command).join('\n');
  const figure = useRef<HTMLElement>(null);
  const progress = useTyping(resolved.entries, animate, figure);
  const [copied, setCopied] = useState(false);
  const statusId = `b10x-terminal-${useId().replaceAll(':', '')}-status`;
  const copy = async (): Promise<void> => {
    try {
      await navigator.clipboard.writeText(commands);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1800);
    } catch {
      setCopied(false);
    }
  };
  return <figure ref={figure} className={['b10x-terminal', tilt && 'b10x-terminal--tilt'].filter(Boolean).join(' ')} aria-label={label}>
    <div className="b10x-terminal__bar">
      <span className="b10x-terminal__lights" aria-hidden="true"><i /><i /><i /></span>
      <span className="b10x-terminal__title">{label}</span>
      <button type="button" className="b10x-terminal__copy" onClick={copy} aria-describedby={statusId}>{copied ? 'Copied' : 'Copy commands'}</button>
      <span className="b10x-sr-only" role="status" id={statusId}>{copied ? 'Commands copied to the clipboard' : ''}</span>
    </div>
    <pre className="b10x-terminal__body" tabIndex={0}><code>{resolved.entries.map((entry, index) => <TerminalLines key={index} entry={entry} prompt={prompt} shown={progress?.[index]} last={index === resolved.entries.length - 1} />)}</code></pre>
    {footer && <figcaption className="b10x-terminal__foot"><span className="b10x-terminal__dot" aria-hidden="true" />{footer}</figcaption>}
  </figure>;
}

function TerminalLines({entry, prompt, shown, last}: {entry: TerminalEntry; prompt: string; shown?: {command: number; output: boolean}; last: boolean}): ReactNode {
  const typed = shown ? entry.command.slice(0, shown.command) : entry.command;
  const rest = shown ? entry.command.slice(shown.command) : '';
  const outputVisible = !shown || shown.output;
  const failed = entry.exitCode !== undefined && entry.exitCode !== 0;
  return <>
    {entry.comment && <span className="b10x-terminal__comment"># {entry.comment}{'\n'}</span>}
    <span className="b10x-terminal__line"><span className="b10x-terminal__prompt" aria-hidden="true">{prompt} </span><span className="b10x-terminal__command">{typed}<span className="b10x-terminal__pending">{rest}</span></span>{'\n'}</span>
    {entry.output !== undefined && entry.output !== '' && <span className={['b10x-terminal__output', failed && 'b10x-terminal__output--failed', !outputVisible && 'b10x-terminal__pending'].filter(Boolean).join(' ')}>{entry.output}{'\n'}</span>}
    {!last && '\n'}
  </>;
}

/** Type the commands once, when the terminal first scrolls into view; the full text is shown until then. */
function useTyping(entries: readonly TerminalEntry[], enabled: boolean, element: {current: HTMLElement | null}): Array<{command: number; output: boolean}> | undefined {
  const [state, setState] = useState<Array<{command: number; output: boolean}> | undefined>(undefined);
  const started = useRef(false);
  useEffect(() => {
    if (!enabled || started.current || typeof window === 'undefined') return;
    if (window.matchMedia?.('(prefers-reduced-motion: reduce)').matches) return;
    let frame = 0;
    const run = (): void => {
      started.current = true;
      const schedule: Array<{entry: number; at: number; chars: number; output: boolean}> = [];
      let time = 300;
      entries.forEach((entry, index) => {
        for (let chars = 1; chars <= entry.command.length; chars += 1) schedule.push({entry: index, at: (time += 28), chars, output: false});
        schedule.push({entry: index, at: (time += 260), chars: entry.command.length, output: true});
        time += 420;
      });
      setState(entries.map(() => ({command: 0, output: false})));
      const begin = performance.now();
      const tick = (now: number): void => {
        const elapsed = now - begin;
        const next = entries.map(() => ({command: 0, output: false}));
        for (const step of schedule) {
          if (step.at > elapsed) break;
          next[step.entry] = {command: step.chars, output: step.output};
        }
        setState(next);
        if (elapsed <= time) frame = window.requestAnimationFrame(tick);
        else setState(undefined);
      };
      frame = window.requestAnimationFrame(tick);
    };
    const target = element.current;
    if (!target || !('IntersectionObserver' in window)) { run(); return () => window.cancelAnimationFrame(frame); }
    const observer = new IntersectionObserver((records) => {
      if (records.some((record) => record.isIntersecting) && !started.current) { observer.disconnect(); run(); }
    }, {threshold: 0.6});
    observer.observe(target);
    return () => { observer.disconnect(); window.cancelAnimationFrame(frame); };
  }, [enabled, entries, element]);
  return state;
}

// ---------------------------------------------------------------------------------------------
// Feature grid, flow, status, related tools
// ---------------------------------------------------------------------------------------------

export interface FeatureProps extends Omit<ProductFeature, 'description'> {
  description?: string;
  children?: ReactNode;
}

/** One card of a `FeatureGrid`, for MDX authors who prefer children to an `items` array. */
export function Feature({title, description, href, status, children}: FeatureProps): ReactNode {
  return <li className="b10x-feature">
    <h3>{href ? <Link to={href}>{title}</Link> : title}</h3>
    {status && <StatusBadge status={status} />}
    {description && <p>{description}</p>}
    {children && <div className="b10x-feature__body">{children}</div>}
  </li>;
}

export interface FeatureGridProps {
  items?: readonly ProductFeature[];
  children?: ReactNode;
  columns?: 2 | 3 | 4;
  label?: string;
}

export function FeatureGrid({items, children, columns = 3, label = 'What it does'}: FeatureGridProps): ReactNode {
  return <ol className={`b10x-feature-grid b10x-feature-grid--${columns}`} aria-label={label}>
    {items?.map((item) => <Feature key={item.title} {...item} />)}
    {children}
  </ol>;
}

export interface FlowStepProps extends ProductFlowStep {children?: ReactNode}

export function FlowStep({label, title, description, children}: FlowStepProps): ReactNode {
  return <li className="b10x-flow__step">
    {label && <span className="b10x-flow__label">{label}</span>}
    <strong>{title}</strong>
    {description && <p>{description}</p>}
    {children}
  </li>;
}

export interface FlowProps {
  steps?: readonly ProductFlowStep[];
  children?: ReactNode;
  label?: string;
}

/** Steps with arrows between them; wraps to a vertical sequence on narrow screens. */
export function Flow({steps, children, label = 'How it works'}: FlowProps): ReactNode {
  const count = (steps?.length ?? 0) + Children.toArray(children).filter(isValidElement).length;
  return <ol className="b10x-flow" aria-label={label} style={{'--b10x-flow-count': count} as CSSProperties}>
    {steps?.map((step) => <FlowStep key={step.title} {...step} />)}
    {children}
  </ol>;
}

const STATUS_ORDER: readonly ProductStatus[] = ['shipped', 'decided', 'planned'];
const STATUS_LABELS: Record<ProductStatus, string> = {shipped: 'Shipped', decided: 'Decided', planned: 'Planned'};

export interface StatusStripProps {
  items: readonly ProductStatusItem[];
  label?: string;
}

/** What exists today and what does not, counted from the items themselves. */
export function StatusStrip({items, label = 'Status'}: StatusStripProps): ReactNode {
  const counts = STATUS_ORDER.map((status) => ({status, count: items.filter((item) => item.status === status).length})).filter((entry) => entry.count > 0);
  const summary = counts.map(({status, count}) => `${count} ${STATUS_LABELS[status].toLowerCase()}`).join(', ');
  return <section className="b10x-status-strip" aria-label={label}>
    <div className="b10x-status-strip__bar" role="img" aria-label={`${items.length} capabilities: ${summary}`}>
      {counts.map(({status, count}) => <span key={status} className={`b10x-status-strip__segment b10x-status-strip__segment--${status}`} style={{flexGrow: count} as CSSProperties} />)}
    </div>
    <ul className="b10x-status-strip__legend" aria-hidden="true">
      {counts.map(({status, count}) => <li key={status}><span className={`b10x-status-strip__key b10x-status-strip__key--${status}`} /><strong>{count}</strong> {STATUS_LABELS[status].toLowerCase()}</li>)}
    </ul>
    <ul className="b10x-status-strip__items">
      {[...items].sort((left, right) => STATUS_ORDER.indexOf(left.status) - STATUS_ORDER.indexOf(right.status)).map((item) => <li key={item.label}>
        <StatusBadge status={item.status} />
        <span className="b10x-status-strip__label">{item.href ? <Link to={item.href}>{item.label}</Link> : item.label}</span>
        {item.detail && <span className="b10x-status-strip__detail">{item.detail}</span>}
      </li>)}
    </ul>
  </section>;
}

export interface RelatedToolsProps {
  tools: readonly RelatedTool[];
  label?: string;
}

export function RelatedTools({tools, label = 'Related tools'}: RelatedToolsProps): ReactNode {
  return <ul className="b10x-related" aria-label={label}>
    {tools.map((tool) => <li key={tool.name}>
      <Link className="b10x-related__card" to={tool.href}>
        <span className="b10x-mark" aria-hidden="true">{tool.mark ?? tool.name.slice(0, 1)}</span>
        <span className="b10x-related__copy">
          <strong>{tool.name}</strong>
          <span>{tool.description}</span>
        </span>
        {tool.status && <StatusBadge status={tool.status} />}
        <span className="b10x-related__arrow" aria-hidden="true">→</span>
      </Link>
    </li>)}
  </ul>;
}

// ---------------------------------------------------------------------------------------------
// Landing page
// ---------------------------------------------------------------------------------------------

export interface ProductHeroProps {
  eyebrow?: ReactNode;
  /** One entry per line; the last line is emphasised. */
  promise: readonly string[];
  lede: ReactNode;
  actions?: readonly ProductAction[];
  meta?: ReactNode;
  aside?: ReactNode;
}

export function ProductHero({eyebrow, promise, lede, actions = [], meta, aside}: ProductHeroProps): ReactNode {
  const lines = promise.length > 1 ? promise.slice(0, -1) : [];
  const emphasis = promise[promise.length - 1];
  return <section className={['b10x-hero', aside ? '' : 'b10x-hero--solo'].filter(Boolean).join(' ')} aria-labelledby="b10x-hero-title">
    <div className="b10x-hero__copy">
      {eyebrow && <p className="b10x-kicker"><span className="b10x-kicker__dot" aria-hidden="true" />{eyebrow}</p>}
      <h1 id="b10x-hero-title">{lines.map((line) => <span key={line}>{line}<br /></span>)}<em>{emphasis}</em></h1>
      <p className="b10x-hero__lede">{lede}</p>
      {actions.length > 0 && <div className="b10x-hero__actions">{actions.map((action) => <Link key={action.href} to={action.href} className={action.kind === 'primary' ? 'b10x-button' : 'b10x-text-link'}>{action.label} <span aria-hidden="true">{action.kind === 'primary' ? '→' : action.href.startsWith('#') ? '↓' : '→'}</span></Link>)}</div>}
      {meta && <p className="b10x-hero__meta">{meta}</p>}
    </div>
    {aside && <div className="b10x-hero__aside">{aside}</div>}
  </section>;
}

export interface ProductSectionProps {
  id?: string;
  /** Section number; renders as `01 / eyebrow`. */
  number?: number;
  eyebrow?: string;
  title: ReactNode;
  lede?: ReactNode;
  children?: ReactNode;
}

export function ProductSection({id, number, eyebrow, title, lede, children}: ProductSectionProps): ReactNode {
  // Register the anchor so Docusaurus link checking knows `#id` exists.
  const links = useBrokenLinks();
  if (id) links.collectAnchor(id);
  const titleId = id ? `${id}-title` : undefined;
  const kicker = [number !== undefined ? String(number).padStart(2, '0') : undefined, eyebrow].filter(Boolean).join(' / ');
  return <section className="b10x-product-section" id={id} aria-labelledby={titleId}>
    <header className="b10x-product-section__header">
      {kicker && <p className="b10x-kicker">{kicker}</p>}
      <h2 id={titleId}>{title}</h2>
      {lede && <p className="b10x-product-section__lede">{lede}</p>}
    </header>
    {children}
  </section>;
}

export function ProductLanding({data}: {data: ProductLandingData}): ReactNode {
  const terminal = data.product.terminal;
  return <div className="b10x-product">
    <ProductHero
      eyebrow={data.product.eyebrow}
      promise={data.product.promise}
      lede={data.product.lede}
      actions={data.product.actions}
      meta={data.product.meta}
      aside={terminal !== undefined ? <Terminal session={terminal} tilt caption={data.product.terminalCaption} /> : undefined}
    />
    {data.sections.map((section, index) => <ProductSection key={`${section.kind}-${index}`} id={sectionId(data.sections, index)} number={index + 1} eyebrow={section.eyebrow} title={section.title} lede={section.lede}>
      <LandingSection section={section} />
    </ProductSection>)}
  </div>;
}

function LandingSection({section}: {section: ProductLandingSection}): ReactNode {
  switch (section.kind) {
    case 'features': return <FeatureGrid items={section.items} />;
    case 'flow': return <Flow steps={section.steps} />;
    case 'status': return <StatusStrip items={section.items} />;
    case 'related': return <RelatedTools tools={section.tools} />;
    case 'terminal': return <Terminal session={section.session} />;
    case 'protocol-graph': return <ProtocolGraph data={section.data} caption={section.caption} />;
    case 'domain-graph': return <DomainGraph data={section.data} caption={section.caption} />;
    default: return null;
  }
}

const SECTION_IDS: Record<ProductLandingSection['kind'], string> = {features: 'what', flow: 'how', status: 'status', related: 'related', terminal: 'try', 'protocol-graph': 'protocol', 'domain-graph': 'domain'};

function sectionId(sections: readonly ProductLandingSection[], index: number): string {
  const base = SECTION_IDS[sections[index].kind];
  const earlier = sections.slice(0, index).filter((section) => section.kind === sections[index].kind).length;
  return earlier ? `${base}-${earlier + 1}` : base;
}

