export type Maturity = 'stable' | 'development' | 'experimental';
export type Availability = 'published' | 'local-only' | 'planned';
export type Discoverability = 'public' | 'unlisted' | 'internal';
export type Journey = 'understand' | 'plan-work' | 'specify' | 'build-agents' | 'operate-services';
export type Audience = 'evaluator' | 'adopter' | 'developer' | 'operator' | 'researcher';

/** Access values accepted in explicit v4 and experience declarations, ordered least to most restrictive. */
export type DeclaredAccess = 'public' | 'account-required' | 'approval-required' | 'private';
/** `unspecified` is derived only while normalizing immutable v1-v3 manifests. */
export type Access = DeclaredAccess | 'unspecified';
export type DeclaredSupport = 'supported' | 'preview' | 'experimental' | 'paused' | 'planned' | 'retired';
/** `unspecified` is derived only while normalizing immutable v1-v3 manifests. */
export type Support = DeclaredSupport | 'unspecified';
export type ArtifactKind = 'documentation' | 'source' | 'package' | 'binary' | 'container' | 'helm-chart' | 'hosted-service';
export type ArtifactAvailability = 'available' | 'unpublished' | 'planned' | 'retired';

export interface ExperienceArtifact {
  id: string;
  kind: ArtifactKind;
  availability: ArtifactAvailability;
  access: DeclaredAccess;
  url?: string;
  version?: string;
  note?: string;
}

export interface AdoptionPath {
  id: string;
  label: string;
  support: DeclaredSupport;
  access: DeclaredAccess;
  artifactIds: string[];
  url?: string;
  estimatedMinutes?: number;
  prerequisites?: string[];
  outcome?: string;
  note?: string;
}

export interface DocumentationExperience {
  id: string;
  label: string;
  summary: string;
  audiences: Audience[];
  /** Array order is presentation and adoption-path order. */
  adoptionPaths: AdoptionPath[];
}

export interface ExperienceCatalog {
  schema: 'b10x-experiences/v1';
  artifacts: ExperienceArtifact[];
  experiences: DocumentationExperience[];
}

export type AdoptionPathBlocker =
  | 'unspecified-contract'
  | 'missing-url'
  | 'private-access'
  | 'non-actionable-support'
  | 'unavailable-artifact';

export interface EvaluatedAdoptionPath extends Omit<AdoptionPath, 'access' | 'support'> {
  access: Access;
  support: Support;
  artifacts: ExperienceArtifact[];
  effectiveAccess: Access;
  actionable: boolean;
  blockers: AdoptionPathBlocker[];
  explanation?: string;
}

export interface EvaluatedDocumentationExperience extends Omit<DocumentationExperience, 'adoptionPaths'> {
  compatibility: boolean;
  adoptionPaths: EvaluatedAdoptionPath[];
}

export interface SurfaceLink {
  label: string;
  url: string;
  kind?: 'docs' | 'quickstart' | 'guide' | 'api' | 'source' | 'security' | 'status' | 'feed' | 'reference';
}

export type FeedFormat = 'rss' | 'json-feed' | 'json';
export type FeedScope = 'impact' | 'releases' | 'all';

export interface SurfaceFeed extends SurfaceLink {
  kind?: 'feed';
  format: FeedFormat;
  scope: FeedScope;
}

export interface SurfaceRelationship {
  target: string;
  kind: 'introduces' | 'informs' | 'specifies' | 'implements' | 'hosts' | 'drives' | 'executes-in' | 'uses' | 'supports';
  label?: string;
}

export interface AdoptionAction {
  label: string;
  url: string;
  mode: 'browser' | 'install' | 'download' | 'source-build' | 'container' | 'hosted';
  estimatedMinutes: number;
  prerequisites?: string[];
  outcome: string;
}

export type SharedComponentName =
  | 'AdoptionCard'
  | 'BoundaryNotice'
  | 'Callout'
  | 'CardGrid'
  | 'CodeExample'
  | 'CodeTabs'
  | 'CommandExample'
  | 'ContentCard'
  | 'DataCatalog'
  | 'DependencyGraph'
  | 'Diagram'
  | 'EcosystemFamilyGateway'
  | 'EcosystemSwitcher'
  | 'FactGrid'
  | 'FilterChipGroup'
  | 'JsonSchemaViewer'
  | 'OpenApiReference'
  | 'PageHeader'
  | 'ProjectCard'
  | 'SearchField'
  | 'SectionHeader'
  | 'StatusBadge';

export interface SourceSelection {
  include: string[];
  exclude?: string[];
}

export interface SpecificationSource {
  id: string;
  format: 'openapi' | 'json-schema';
  path: string;
  route: string;
  title?: string;
}

export interface SourceNavigation {
  label?: string;
  group?: string;
  order?: number;
  sidebar: 'autogenerated' | 'flat';
}

/** Data-only files an owning repository permits the unified website to publish. */
export interface SurfaceSource {
  root: string;
  documents?: SourceSelection;
  data?: SourceSelection;
  assets?: SourceSelection;
  blog?: SourceSelection;
  specifications?: SpecificationSource[];
  navigation?: SourceNavigation;
  components?: SharedComponentName[];
}

export interface DocumentationDelivery {
  publisher: 'website';
  repository: 'beyond10x.github.io';
  origin: 'https://beyond10x.github.io';
}

export interface DocumentationSurface {
  id: string;
  name: string;
  summary: string;
  kind: 'front-door' | 'documentation' | 'research' | 'service-docs' | 'reference' | 'updates';
  canonicalUrl: string;
  maturity: Maturity;
  availability: Availability;
  discoverability: Discoverability;
  audiences?: Audience[];
  journeys: Journey[];
  capabilities: string[];
  sections: SurfaceLink[];
  relationships?: SurfaceRelationship[];
  feeds?: Array<SurfaceLink | SurfaceFeed>;
  adoption?: AdoptionAction;
  accent?: string;
  mark?: string;
  shell: {integration: 'docusaurus' | 'portable'; revision: string};
}

export interface DocumentationSurfaceV3 extends Omit<DocumentationSurface, 'feeds' | 'shell'> {
  audiences: Audience[];
  primaryJourney: Journey;
  routeBase: string;
  source: SurfaceSource;
  feeds?: SurfaceFeed[];
}

export interface DocumentationRepository {
  id: string;
  url: string;
  displayName?: string;
}

export interface DocumentationRepositoryV3 extends DocumentationRepository {
  displayName: string;
}

export interface DocumentationManifestLegacy {
  schema: 'b10x-docs/v1' | 'b10x-docs/v2';
  repository: DocumentationRepository;
  surfaces: DocumentationSurface[];
}

export interface DocumentationManifestV3 {
  schema: 'b10x-docs/v3';
  repository: DocumentationRepositoryV3;
  delivery: DocumentationDelivery;
  journeyPaths?: Partial<Record<Journey, string[]>>;
  surfaces: DocumentationSurfaceV3[];
}

export interface DocumentationPublication {
  availability: Availability;
  discoverability: Discoverability;
}

export interface DocumentMetadataDefaults {
  audiences: Audience[];
  experienceIds: string[];
  support: DeclaredSupport;
  access: DeclaredAccess;
}

/** The validated value of the top-level `b10x` Markdown/MDX frontmatter property. */
export interface DocumentPageMetadata {
  schema: 'b10x-doc-page/v1';
  audiences: Audience[];
  experienceIds: string[];
  support?: DeclaredSupport;
  access?: DeclaredAccess;
}

export interface EffectiveDocumentPageMetadata {
  audiences: Audience[];
  experienceIds: string[];
  support: Support;
  access: Access;
  compatibility: boolean;
}

export interface ResolvedDocumentPageMetadata {
  declared?: DocumentPageMetadata;
  effective: EffectiveDocumentPageMetadata;
}

export interface DocumentationSurfaceV4 {
  id: string;
  name: string;
  summary: string;
  kind: DocumentationSurface['kind'];
  canonicalUrl: string;
  maturity: Maturity;
  publication: DocumentationPublication;
  experienceIds: string[];
  documentDefaults: DocumentMetadataDefaults;
  /** Retained only for compatibility projections; experiences are authoritative in v4. */
  primaryJourney?: Journey;
  /** Retained only for compatibility projections; experiences are authoritative in v4. */
  journeys?: Journey[];
  capabilities: string[];
  sections: SurfaceLink[];
  relationships?: SurfaceRelationship[];
  feeds?: SurfaceFeed[];
  accent?: string;
  mark?: string;
  routeBase: string;
  source: SurfaceSource;
}

export interface DocumentationManifestV4 {
  schema: 'b10x-docs/v4';
  repository: DocumentationRepositoryV3;
  delivery: DocumentationDelivery;
  surfaces: DocumentationSurfaceV4[];
}

export type DocumentationManifest = DocumentationManifestLegacy | DocumentationManifestV3 | DocumentationManifestV4;

export type AnyDocumentationSurface = DocumentationSurface | DocumentationSurfaceV3 | DocumentationSurfaceV4;

export type RegistrySurface = (DocumentationSurface | DocumentationSurfaceV3 | (DocumentationSurfaceV4 & {
  availability: Availability;
  discoverability: Discoverability;
  audiences: Audience[];
  journeys: Journey[];
})) & {
  key: string;
  repository: DocumentationRepository;
};

export interface EcosystemRegistry {
  schema: 'b10x-docs-registry/v2';
  surfaces: RegistrySurface[];
}

export interface ManifestExperienceSurface {
  surfaceKey: string;
  compatibility: boolean;
  experienceIds: string[];
  experiences: EvaluatedDocumentationExperience[];
}

export type ChangeKind = 'release' | 'capability' | 'migration' | 'breaking' | 'deprecation' | 'security' | 'research';
export type ChangeImpact = 'notable' | 'significant' | 'action-required';
export type ChangeRelationKind = 'enables' | 'depends-on' | 'integrates-with' | 'migrates' | 'supersedes' | 'deprecates';

export interface ChangeCore {
  id: string;
  repository: string;
  publishedAt: string;
  title: string;
  summary: string;
  kind: ChangeKind;
  impact: ChangeImpact;
  source: {url: string; version?: string};
  journeys: Journey[];
  relations?: Array<{target: string; kind: ChangeRelationKind; label?: string}>;
  action?: {label: string; url: string};
}

export interface EcosystemChangeV1 extends ChangeCore {
  schema: 'b10x-change/v1';
  affectedSurfaces: string[];
}

export interface ChangeTargets {
  repositories?: string[];
  surfaces?: string[];
  components?: string[];
  apis?: string[];
}

export interface EcosystemChangeV2 extends ChangeCore {
  schema: 'b10x-change/v2';
  affected: ChangeTargets;
}

export type EcosystemChange = EcosystemChangeV1 | EcosystemChangeV2;

export interface ReleaseFact {
  repository: string;
  version: string;
  publishedAt: string;
  url: string;
}

export interface ReleaseFactsDocument {
  schema: 'b10x-release-facts/v1';
  releases: ReleaseFact[];
}

export interface ChangeLedgerEntry extends ChangeCore {
  key: string;
  automatic: boolean;
  channel: 'impact' | 'releases';
  affectedSurfaces: string[];
  affectedRepositories?: string[];
  affectedComponents?: string[];
  affectedApis?: string[];
}

export interface ChangeLedger {
  schema: 'b10x-change-ledger/v1';
  changes: ChangeLedgerEntry[];
}

export type CollectedSourceKind = 'document' | 'data' | 'blog' | 'asset' | 'openapi' | 'json-schema';

export interface CollectedSource {
  repository: string;
  surface: string;
  kind: CollectedSourceKind;
  sourcePath: string;
  outputPath: string;
  sha256: string;
  size: number;
  specificationId?: string;
  route?: string;
}

export interface CollectionIndex {
  schema: 'b10x-docs-collection/v1';
  repository: DocumentationRepositoryV3;
  files: CollectedSource[];
  contentSha256: string;
}

export interface IndexedDocumentPage {
  repository: string;
  surface: string;
  kind: 'document' | 'blog';
  sourcePath: string;
  outputPath: string;
  declared?: DocumentPageMetadata;
  effective: EffectiveDocumentPageMetadata;
}

/** Metadata projection kept separate so b10x-docs-collection/v1 remains byte-for-byte stable. */
export interface DocumentPageIndex {
  schema: 'b10x-doc-index/v1';
  repository: DocumentationRepositoryV3;
  pages: IndexedDocumentPage[];
}

export interface SourceLockEntry {
  repository: string;
  url: string;
  commit: string;
  manifestPath: string;
  manifestSha256: string;
  contentSha256: string;
}

export interface SourceLock {
  schema: 'b10x-sources/v1';
  sources: SourceLockEntry[];
}

export interface HtmlRedirect {
  from: string;
  to: string;
  type: 'html';
}

export interface StaticAlias {
  from: string;
  source: string;
  type: 'alias';
  mediaType?: string;
}

export interface RedirectMap {
  schema: 'b10x-redirects/v1';
  origin: string;
  redirects: Array<HtmlRedirect | StaticAlias>;
}
